### PR TITLE
alert issue fixed

### PR DESCRIPTION
**Pull request by v-hearya**

### CODE REVIEW

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/configure-xmpp-gateway-on-lync-server-2013_1.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/configure-xmpp-gateway-on-lync-server-2013_1.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/configure-xmpp-gateway-on-lync-server-2013_1?branch=pr-de-de-41) |
[server-2013/lync-server-2013-choosing-a-topology.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/lync-server-2013-choosing-a-topology.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/lync-server-2013-choosing-a-topology?branch=pr-de-de-41) |
[server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server?branch=pr-de-de-41) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C22%5C51d551d4-4968-6f8e-48ca-4e205167b597%5CPullRequest%5C201808222350184412-41%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=d3hkQK3TkOhLuwZ%2Fej8x%2B91rGbAQTdRRAdVpJAuYnB8%3D&st=2018-08-22T23%3A47%3A18Z&se=2018-09-22T23%3A52%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/configure-xmpp-gateway-on-lync-server-2013_1.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/configure-xmpp-gateway-on-lync-server-2013_1.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/configure-xmpp-gateway-on-lync-server-2013_1?branch=pr-de-de-41) |
[server-2013/lync-server-2013-choosing-a-topology.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/lync-server-2013-choosing-a-topology.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/lync-server-2013-choosing-a-topology?branch=pr-de-de-41) |
[server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server?branch=pr-de-de-41) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C22%5C51d551d4-4968-6f8e-48ca-4e205167b597%5CPullRequest%5C201808222357290313-41%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kLspGtE2R8cLggwuY2MV%2BamxSmT4Gd0ZbffjJN8M82o%3D&st=2018-08-22T23%3A54%3A52Z&se=2018-09-22T23%3A59%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/configure-xmpp-gateway-on-lync-server-2013_1.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/configure-xmpp-gateway-on-lync-server-2013_1.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/configure-xmpp-gateway-on-lync-server-2013_1?branch=pr-de-de-41) |
[server-2013/lync-server-2013-choosing-a-topology.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/lync-server-2013-choosing-a-topology.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/lync-server-2013-choosing-a-topology?branch=pr-de-de-41) |
[server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server?branch=pr-de-de-41) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C23%5C51d551d4-4968-6f8e-48ca-4e205167b597%5CPullRequest%5C201808230006477703-41%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ud6LJqhgvgTnBovzPvLPK%2FsSu%2BqG91LCv%2F%2FKvqJhtsY%3D&st=2018-08-23T00%3A04%3A52Z&se=2018-09-23T00%3A09%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/configure-xmpp-gateway-on-lync-server-2013_1.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/configure-xmpp-gateway-on-lync-server-2013_1.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/configure-xmpp-gateway-on-lync-server-2013_1?branch=pr-de-de-41) |
[server-2013/lync-server-2013-choosing-a-topology.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/lync-server-2013-choosing-a-topology.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/lync-server-2013-choosing-a-topology?branch=pr-de-de-41) |
[server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server?branch=pr-de-de-41) |
[server-2013/lync-server-2013-deploying-lync-web-app.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/lync-server-2013-deploying-lync-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/lync-server-2013-deploying-lync-web-app?branch=pr-de-de-41) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C23%5C51d551d4-4968-6f8e-48ca-4e205167b597%5CPullRequest%5C201808230007352225-41%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=udlqBwKRtmZMhgFefmPB87DHvPSc6R28xRszebie8Dw%3D&st=2018-08-23T00%3A08%3A34Z&se=2018-09-23T00%3A13%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/configure-xmpp-gateway-on-lync-server-2013_1.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/configure-xmpp-gateway-on-lync-server-2013_1.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/configure-xmpp-gateway-on-lync-server-2013_1?branch=pr-de-de-41) |
[server-2013/lync-server-2013-choosing-a-topology.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/lync-server-2013-choosing-a-topology.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/lync-server-2013-choosing-a-topology?branch=pr-de-de-41) |
[server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server?branch=pr-de-de-41) |
[server-2013/lync-server-2013-deploying-lync-web-app.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/lync-server-2013-deploying-lync-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/lync-server-2013-deploying-lync-web-app?branch=pr-de-de-41) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C23%5C51d551d4-4968-6f8e-48ca-4e205167b597%5CPullRequest%5C201808230012392140-41%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=dbtEnDL90DiNVAlfXmLTJ9DeKd6PYYwf1IdwxLloU8I%3D&st=2018-08-23T00%3A11%3A33Z&se=2018-09-23T00%3A16%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/configure-xmpp-gateway-on-lync-server-2013_1.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/configure-xmpp-gateway-on-lync-server-2013_1.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/configure-xmpp-gateway-on-lync-server-2013_1?branch=pr-de-de-41) |
[server-2013/lync-server-2013-choosing-a-topology.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/lync-server-2013-choosing-a-topology.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/lync-server-2013-choosing-a-topology?branch=pr-de-de-41) |
[server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server?branch=pr-de-de-41) |
[server-2013/lync-server-2013-deploying-lync-web-app.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/lync-server-2013-deploying-lync-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/lync-server-2013-deploying-lync-web-app?branch=pr-de-de-41) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C23%5C51d551d4-4968-6f8e-48ca-4e205167b597%5CPullRequest%5C201808230029252880-41%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=F1Q44ORs7whmXWlZGXGO9d4M5n416f4zuCN%2BET2sK7Q%3D&st=2018-08-23T00%3A27%3A21Z&se=2018-09-23T00%3A32%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/configure-xmpp-gateway-on-lync-server-2013_1.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/configure-xmpp-gateway-on-lync-server-2013_1.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/configure-xmpp-gateway-on-lync-server-2013_1?branch=pr-de-de-41) |
[server-2013/lync-server-2013-choosing-a-topology.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/lync-server-2013-choosing-a-topology.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/lync-server-2013-choosing-a-topology?branch=pr-de-de-41) |
[server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server?branch=pr-de-de-41) |
[server-2013/lync-server-2013-deploying-lync-web-app.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.de-de/blob/master/server-2013/lync-server-2013-deploying-lync-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/office/lync-server-2013/lync-server-2013-deploying-lync-web-app?branch=pr-de-de-41) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C23%5C51d551d4-4968-6f8e-48ca-4e205167b597%5CPullRequest%5C201808230031323307-41%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Lr5b8n3wvJ6VrXQSDeOawpj1kbGxqm5fCfYcwhFGWlo%3D&st=2018-08-23T00%3A30%3A21Z&se=2018-09-23T00%3A35%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Review by DanMSFT — APPROVED** [review]

**Pull request merged**
